n1 = input('Digite Algo:')
print('O tipo primitivo é',type(n1))
print('É numérico?',n1.isnumeric())
print('È alfanumérico?',n1.isalnum())
print('É Espaço?',n1.isspace())
print('É um dígito?',n1.isdigit())
print('Está digitado em maiúsculo?',n1.isupper())
